
-- BEGINNER LEVEL


-- 1. Total Orders
SELECT COUNT(order_id) AS total_orders
FROM orders;



-- 2. Total Quantity Sold
SELECT SUM(quantity) AS total_pizzas_sold
FROM order_details;



-- 3. Pizza Price List
SELECT pt.name,
       p.size,
       p.price
FROM pizzas p
JOIN pizza_types pt
ON p.pizza_type_id = pt.pizza_type_id
ORDER BY p.price DESC;



-- 4. Unique Pizza Categories
SELECT DISTINCT category
FROM pizza_types;



-- 5. Most Expensive Pizza
SELECT pt.name,
       p.price
FROM pizzas p
JOIN pizza_types pt
ON p.pizza_type_id = pt.pizza_type_id
ORDER BY p.price DESC
LIMIT 1;



-- BASIC TO INTERMEDIATE LEVEL

-- 6. Orders Per Day
SELECT date,
       COUNT(order_id) AS total_orders
FROM orders
GROUP BY date
ORDER BY date;



-- 7. Most Ordered Pizza
SELECT pt.name,
       SUM(od.quantity) AS total_quantity
FROM pizza_types pt
JOIN pizzas p
ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
ON p.pizza_id = od.pizza_id
GROUP BY pt.name
ORDER BY total_quantity DESC
LIMIT 1;



-- 8. Orders by Pizza Size
SELECT p.size,
       SUM(od.quantity) AS total_quantity
FROM pizzas p
JOIN order_details od
ON p.pizza_id = od.pizza_id
GROUP BY p.size
ORDER BY total_quantity DESC;



-- 9. Top 5 Most Ordered Pizzas
SELECT pt.name,
       SUM(od.quantity) AS total_quantity
FROM pizza_types pt
JOIN pizzas p
ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
ON p.pizza_id = od.pizza_id
GROUP BY pt.name
ORDER BY total_quantity DESC
LIMIT 5;



-- 10. Category Wise Pizza Count
SELECT category,
       COUNT(name) AS total_pizzas
FROM pizza_types
GROUP BY category
ORDER BY total_pizzas DESC;




-- INTERMEDIATE LEVEL


-- 11. Revenue Generated by Each Pizza
SELECT pt.name,
       ROUND(SUM(od.quantity * p.price)::NUMERIC, 2) AS total_revenue
FROM pizza_types pt
JOIN pizzas p
ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
ON p.pizza_id = od.pizza_id
GROUP BY pt.name
ORDER BY total_revenue DESC;



-- 12. Total Revenue
SELECT ROUND(SUM(od.quantity * p.price)::NUMERIC, 2) AS total_revenue
FROM order_details od
JOIN pizzas p
ON od.pizza_id = p.pizza_id;



-- 13. Revenue by Category
SELECT pt.category,
       ROUND(SUM(od.quantity * p.price)::NUMERIC, 2) AS total_revenue
FROM pizza_types pt
JOIN pizzas p
ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
ON p.pizza_id = od.pizza_id
GROUP BY pt.category
ORDER BY total_revenue DESC;



-- 14. Peak Ordering Hours
SELECT EXTRACT(HOUR FROM time) AS order_hour,
       COUNT(order_id) AS total_orders
FROM orders
GROUP BY order_hour
ORDER BY order_hour;



-- 15. Average Price by Pizza Size
SELECT size,
       ROUND(AVG(price)::NUMERIC, 2) AS average_price
FROM pizzas
GROUP BY size
ORDER BY average_price DESC;



-- INTERMEDIATE TO ADVANCED LEVEL


-- 16. Most Sold Category
SELECT pt.category,
       SUM(od.quantity) AS total_quantity
FROM pizza_types pt
JOIN pizzas p
ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
ON p.pizza_id = od.pizza_id
GROUP BY pt.category
ORDER BY total_quantity DESC
LIMIT 1;



-- 17. Pizzas Never Ordered
SELECT p.pizza_id,
       pt.name,
       p.size
FROM pizzas p
JOIN pizza_types pt
ON p.pizza_type_id = pt.pizza_type_id
LEFT JOIN order_details od
ON p.pizza_id = od.pizza_id
WHERE od.pizza_id IS NULL;



-- 18. Orders Containing More Than 3 Pizzas
SELECT order_id,
       SUM(quantity) AS total_quantity
FROM order_details
GROUP BY order_id
HAVING SUM(quantity) > 3;



-- 19. Highest Revenue Generating Pizza Size
SELECT p.size,
       ROUND(SUM(od.quantity * p.price)::NUMERIC, 2) AS total_revenue
FROM pizzas p
JOIN order_details od
ON p.pizza_id = od.pizza_id
GROUP BY p.size
ORDER BY total_revenue DESC
LIMIT 1;



-- 20. Orders with Above Average Quantity
SELECT order_id,
       SUM(quantity) AS total_quantity
FROM order_details
GROUP BY order_id
HAVING SUM(quantity) >
(
    SELECT AVG(order_qty)
    FROM
    (
        SELECT SUM(quantity) AS order_qty
        FROM order_details
        GROUP BY order_id
    ) AS avg_table
);




-- ADVANCED LEVEL


-- 21. Second Most Expensive Pizza
SELECT name,
       price
FROM
(
    SELECT pt.name,
           p.price,
           DENSE_RANK() OVER(ORDER BY p.price DESC) AS price_rank
    FROM pizzas p
    JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
) AS ranked_pizzas
WHERE price_rank = 2;



-- 22. Category with Maximum Revenue
SELECT pt.category,
       ROUND(SUM(od.quantity * p.price)::NUMERIC, 2) AS total_revenue
FROM pizza_types pt
JOIN pizzas p
ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od
ON p.pizza_id = od.pizza_id
GROUP BY pt.category
ORDER BY total_revenue DESC
LIMIT 1;



-- 23. Top Pizza for Each Category
SELECT category,
       name,
       total_quantity
FROM
(
    SELECT pt.category,
           pt.name,
           SUM(od.quantity) AS total_quantity,
           RANK() OVER
           (
               PARTITION BY pt.category
               ORDER BY SUM(od.quantity) DESC
           ) AS ranking
    FROM pizza_types pt
    JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
    JOIN order_details od
    ON p.pizza_id = od.pizza_id
    GROUP BY pt.category, pt.name
) AS ranked_pizzas
WHERE ranking = 1;



-- 24. Orders with Multiple Pizza Types
SELECT order_id,
       COUNT(DISTINCT pizza_id) AS unique_pizza_types
FROM order_details
GROUP BY order_id
HAVING COUNT(DISTINCT pizza_id) > 1;



-- 25. Running Total of Revenue by Date
SELECT date,
       SUM(daily_revenue)
       OVER(ORDER BY date) AS cumulative_revenue
FROM
(
    SELECT o.date,
           SUM(od.quantity * p.price) AS daily_revenue
    FROM orders o
    JOIN order_details od
    ON o.order_id = od.order_id
    JOIN pizzas p
    ON od.pizza_id = p.pizza_id
    GROUP BY o.date
) AS revenue_table;



-- CTE BASED QUESTIONS


-- 26. Daily Revenue using CTE
WITH DailyRevenueCTE AS
(
    SELECT o.date,
           ROUND(SUM(od.quantity * p.price)::NUMERIC, 2) AS daily_revenue
    FROM orders o
    JOIN order_details od
    ON o.order_id = od.order_id
    JOIN pizzas p
    ON od.pizza_id = p.pizza_id
    GROUP BY o.date
)

SELECT *
FROM DailyRevenueCTE
ORDER BY date;



-- 27. Top 3 Pizzas by Revenue using CTE
WITH PizzaRevenueCTE AS
(
    SELECT pt.name,
           SUM(od.quantity * p.price) AS revenue
    FROM pizza_types pt
    JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
    JOIN order_details od
    ON p.pizza_id = od.pizza_id
    GROUP BY pt.name
)

SELECT name,
       ROUND(revenue::NUMERIC, 2) AS total_revenue
FROM PizzaRevenueCTE
ORDER BY revenue DESC
LIMIT 3;



-- 28. Ranking Pizzas by Revenue
WITH PizzaRevenueRank AS
(
    SELECT pt.name,
           ROUND(SUM(od.quantity * p.price)::NUMERIC, 2) AS total_revenue
    FROM pizza_types pt
    JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
    JOIN order_details od
    ON p.pizza_id = od.pizza_id
    GROUP BY pt.name
)

SELECT name,
       total_revenue,
       RANK() OVER(ORDER BY total_revenue DESC) AS revenue_rank
FROM PizzaRevenueRank;



-- 29. Average Order Value using CTE
WITH OrderTotals AS
(
    SELECT od.order_id,
           SUM(od.quantity * p.price) AS order_revenue
    FROM order_details od
    JOIN pizzas p
    ON od.pizza_id = p.pizza_id
    GROUP BY od.order_id
)

SELECT ROUND(AVG(order_revenue)::NUMERIC, 2) AS average_order_value
FROM OrderTotals;



-- 30. Category wise Revenue Contribution
WITH CategoryRevenue AS
(
    SELECT pt.category,
           SUM(od.quantity * p.price) AS revenue
    FROM pizza_types pt
    JOIN pizzas p
    ON pt.pizza_type_id = p.pizza_type_id
    JOIN order_details od
    ON p.pizza_id = od.pizza_id
    GROUP BY pt.category
)

SELECT category,
       ROUND(revenue::NUMERIC, 2) AS category_revenue,
       ROUND
       (
           (
               revenue /
               (SELECT SUM(revenue) FROM CategoryRevenue)
           )::NUMERIC * 100,
           2
       ) AS percentage_contribution
FROM CategoryRevenue
ORDER BY percentage_contribution DESC;